package com.label305.kama.auth.objects;

import com.j256.ormlite.field.DatabaseField;


@Deprecated
public class AuthData {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @DatabaseField(unique = true)
    private String token;

    @SuppressWarnings("UnusedDeclaration")
    public AuthData() {
        //needed for ormlite
    }

    public AuthData(final String token) {
        setToken(token);
    }

    public String getToken() {
        return token;
    }

    public void setToken(final String token) {
        if (token != null) {
            this.token = token;
        } else {
            this.token = "";
        }
    }
}
