package com.label305.kamav2_android.objects;

import com.j256.ormlite.field.DatabaseField;


public class AuthData {
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;

	@DatabaseField(unique = true)
	private String token;

	public AuthData() {
		//needed for ormlite
	}

	public AuthData(String token) {
		setToken(token);
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		if(token != null) this.token = token;
		else this.token = "";
	}
}
